devops/ambiente_banco/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,HiddenField, IntegerField
from wtforms.validators import DataRequired
from devops.models import AmbienteBanco


class FormularioAmbienteBanco(FlaskForm):
    id = IntegerField('ID')
    descricao = StringField('Descrição',
                            validators=[DataRequired()])
    submit = SubmitField('Salvar')  

devops/ambiente_banco/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, request, Blueprint, flash, redirect,url_for
from devops.models import AmbienteBanco
from devops.ambiente_banco.forms import FormularioAmbienteBanco
from devops import db, app, bread
from flask_login import login_required
from devops.utils.check_roles import require_admin
from flask_breadcrumbs import register_breadcrumb

ambientes_banco = Blueprint('ambientes_banco',__name__,url_prefix='/ambientes_banco')

@ambientes_banco.route('/ambientes_banco')
@login_required
@require_admin()
@register_breadcrumb(ambientes_banco,'.','Ambiente Banco')
def ambiente_banco_list():
    page = request.args.get('page',1,type=int)
    total = len(AmbienteBanco.query.all())
    per_page = 10
    next = None
    previous = None
    if page > 1:
        previous = page - 1
    if page < total/per_page:
        next = page + 1 
    ambientes_banco = AmbienteBanco.query.paginate(page=page,per_page=per_page)
    return render_template('ambiente_banco/list.html',
                            title='Ambientes de Banco',
                            ambientes_banco=ambientes_banco,
                            next=next,
                            previous=previous,
                            total=total)

@ambientes_banco.route('/ambiente_banco/novo',methods=['GET','POST'])
@login_required
@require_admin()
@register_breadcrumb(app,'.','Ambiente Banco')
def ambiente_banco_novo():
    form = FormularioAmbienteBanco()
    if form.validate_on_submit():
        ambiente_banco = AmbienteBanco(descricao=form.descricao.data)
        db.session.add(ambiente_banco)
        db.session.commit()
        flash('Ambiente Cadastrado.','success')
        return redirect(url_for('ambientes_banco.ambiente_banco_list'))
    elif request.method == 'GET':
        return render_template('ambiente_banco/new.html',titulo="Novo Ambiente",form=form)
    else:
        return render_template('ambiente_banco/new.html',titulo="Novo Ambiente",form=form)

@ambientes_banco.route('/ambiente_banco/<int:id_ambiente_banco>')
@login_required
@require_admin()
@register_breadcrumb(app,'.','Ambiente Banco')
def ambiente_banco(id_ambiente_banco):
    ambiente_banco = AmbienteBanco.query.get_or_404(id_ambiente_banco)
    form = FormularioAmbienteBanco()
    form.id.data = ambiente_banco.id
    form.descricao.data = ambiente_banco.descricao
    return render_template('ambiente_banco/show.html',ambiente_banco=ambiente_banco,form=form,title='Ambiente de Banco')

@ambientes_banco.route('/ambiente_banco/<int:id_ambiente_banco>/atualizar',methods=['GET'])
@login_required
@require_admin()
@register_breadcrumb(app,'.','Ambiente Banco')
def editar_ambiente_banco(id_ambiente_banco):
    ambiente_banco = AmbienteBanco.query.get_or_404(id_ambiente_banco)
    form = FormularioAmbienteBanco()
    form.descricao.data = ambiente_banco.descricao
    return render_template('ambiente_banco/edit.html',
                            titulo='Atualizar Ambiente de Banco',
                            ambiente_banco=ambiente_banco,
                            form=form,
                            id_ambiente_banco=id_ambiente_banco)

@ambientes_banco.route('/ambiente_banco/<int:id_ambiente_banco>/atualizar',methods=['POST'])
@login_required
@require_admin()
@register_breadcrumb(app,'.','Ambiente Banco')
def atualizar_ambiente_banco(id_ambiente_banco):
    ambiente_banco = AmbienteBanco.query.get_or_404(id_ambiente_banco)
    form = FormularioAmbienteBanco()
    if form.validate_on_submit():
        ambiente_banco.descricao = form.descricao.data
        
        db.session.commit()
        flash('Registro atualizado!','success')
        return redirect(url_for('ambientes_banco.ambiente_banco_list'))
    else:
        return render_template('ambiente_banco/edit.html',
                            titulo='Atualizar Ambiente de Banco',
                            ambiente_banco=ambiente_banco,
                            form=form,
                            id_ambiente_banco=id_ambiente_banco)

@ambientes_banco.route('/ambiente_banco/<int:id_ambiente_banco>/remover',methods=['GET','POST'])
@login_required
@require_admin()
@register_breadcrumb(app,'.','Ambiente Banco')
def remover_ambiente_banco(id_ambiente_banco):
    print(id_ambiente_banco)
    ambiente_banco = AmbienteBanco.query.get_or_404(id_ambiente_banco)
    db.session.delete(ambiente_banco)
    db.session.commit()
    flash('O registro foi excluído.','success')
    return redirect(url_for('ambientes_banco.ambiente_banco_list'))
    

devops/templates/ambiente_banco/edit.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('ambientes_banco.atualizar_ambiente_banco',id_ambiente_banco=id_ambiente_banco)}}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.descricao.label(class="form-control-label") }}
                            {{ form.descricao(class="form-control") }}
                        
                        </div>
                         <div class="general-button">
                                <a href="{{ url_for('ambientes_banco.ambiente_banco_list') }}" class="btn btn-secondary mb-1">
                                        Voltar
                                </a>
                                
                                {{ form.submit(class="btn btn-primary mb-1") }}
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

devops/templates/ambiente_banco/list.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
                    <div class="row">
                        <div class="table-responsive">
                            {% if ambientes_banco.items %}
                            <table class="table table-boredered">
                                <thead>
                                    <th>#ID</th>
                                    <th>Descrição</th>
                                    <th>Ações</th>
                                </thead>
                                <tbody>
                                    {% for ambiente_banco in ambientes_banco.items %}
                                    <tr>
                                        <td>{{ ambiente_banco.id }}</td>
                                        <td>
                                            <a href="{{ url_for('ambientes_banco.ambiente_banco',id_ambiente_banco=ambiente_banco.id) }}">
                                                {{ ambiente_banco.descricao }}
                                            </a>
                                        </td>
                                        <td>
                                            <span>
                                                <a href="{{ url_for('ambientes_banco.editar_ambiente_banco',id_ambiente_banco=ambiente_banco.id) }}"
                                                    data-toggle="tooltip" data-placement="top" title="Editar">
                                                    <i class="fa fa-pencil color-muted m-r-5"></i>
                                                </a>
                                                <a href="#" data-toggle="modal" data-target="#deleteModal_{{ambiente_banco.id}}"
                                                    data-placement="top" title="Remover">
                                                    <i class="fa fa-close color-danger m-r-5"></i>
                                                </a>
                                                <div class="modal fade" id="deleteModal_{{ambiente_banco.id}}">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Excluir</h5>
                                                                <button type="button" class="close"
                                                                    data-dismiss="modal"><span>&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">Deseja realmente excluir esse item?
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary"
                                                                    data-dismiss="modal">Cancelar</button>
                                                                <form
                                                                    action="{{ url_for('ambientes_banco.remover_ambiente_banco',id_ambiente_banco=ambiente_banco.id) }}"
                                                                    method="POST">
                                                                    <button type="submit"
                                                                        class="btn btn-primary">Excluir</button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                                <div class="row align-items-center">
                                    <div class="media-body">
                                        <h4 class="mb-1 text-muted">Sem itens</h4>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row">
                        {% if ambientes_banco.items %}
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info">
                                Total de {{ total }}
                            </div>
                        </div>
                        {% endif %}
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginage paging_simple_numbers">
                                <ul class="pagination">
                                    {% if previous %}
                                    <li class="paginage_button page-item next">
                                        <a href="{{ url_for('ambientes_banco.ambiente_banco_list',page=previous) }}" data-dt-idx="{{previous}}"
                                            class=page-link>
                                            Próximo
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% for page_num in ambientes_banco.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
                                    {% if page_num %}

                                    {% if ambientes_banco.page == page_num %}
                                    <li class="paginage_button page-item active">
                                        <a href="{{ url_for('ambientes_banco.ambiente_banco_list',page=page_num )}}" data-dt-idx="{{page_num}}"
                                            class=page-link>
                                            {{page_num}}
                                        </a>
                                    </li>
                                    {% else %}
                                    <li class="paginage_button page-item">
                                        <a href="{{ url_for('ambientes_banco.ambiente_banco_list',page=page_num) }}" data-dt-idx="{{page_num}}"
                                            class=page-link>
                                            {{page_num}}
                                        </a>
                                    </li>
                                    {% endif %}

                                    {% else %}
                                    <li class="paginate_button page-item inactive">
                                        ...
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if next %}
                                    <li class="paginage_button page-item next">
                                        <a href="{{ url_for('ambientes_banco.ambiente_banco_list',page=next) }}" data-dt-idx="{{next}}"
                                            class=page-link>
                                            Próximo
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <a href="{{ url_for('ambientes_banco.ambiente_banco_novo') }}">
                <button class="btn btn-primary">
                    Novo
                </button>
            </a>
        </div>
    </div>
</div>

{% endblock  %}

devops/templates/ambiente_banco/new.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('ambientes_banco.ambiente_banco_novo')}}">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.descricao.label(class="form-control-label") }}
                                {% if form.descricao.errors %}
                                    {{ form.descricao(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.descricao.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.descricao(class="form-control") }}
                                {% endif %}
                            </div>
                            
                            <div class="general-button">
                                    <a href="{{ url_for('ambientes_banco.ambiente_banco_list') }}" class="btn btn-secondary md-1">
                                        Voltar
                                    </a>
                                    {{ form.submit(class="btn btn-primary md-1") }}
                            </div>
                            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('nome').focus();
</script>
{% endblock  %}

devops/templates/ambiente_banco/show.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
                    <ul class="card-profile__info">
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.id.label }}:
                            </strong> 
                            <span>
                                {{ form.id.data }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.descricao.label }}:
                            </strong> 
                            <span>
                                {{ form.descricao.data }}
                            </span>
                        </li>
                    </ul>
                    <div class="general-button">
                        <a href="{{ url_for('ambientes_banco.ambiente_banco_list') }}" class="btn btn-secondary md-1">
                            Voltar
                        </a>
                        <a href="{{ url_for('ambientes_banco.editar_ambiente_banco',id_ambiente_banco=form.id.data) }}">
                            <button type="button" class="btn mb-1 btn-primary">
                                Editar
                            </button>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#deleteModal">
                            <button type="button" class="btn mb-1 btn-danger">
                                Excluir
                            </button>
                        </a>
                        <div class="modal fade" id="deleteModal">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Excluir</h5>
                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Deseja realmente excluir esse item?</div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <form action="{{ url_for('ambientes_banco.remover_ambiente_banco',id_ambiente_banco=form.id.data) }}" method="POST">
                                                <button type="submit" class="btn btn-primary">Excluir</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}