devops/situacao_solicitacao/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, IntegerField, BooleanField
from wtforms.validators import DataRequired, Length,ValidationError
from devops.models import SituacaoSolicitacao

class FormularioSituacaoSolicitacao(FlaskForm):
    id = IntegerField('ID')
    descricao = StringField('Descrição',validators=[DataRequired(),Length(min=4,max=20)])
    ativo = BooleanField('Ativo')
    padrao_nova = BooleanField('Padrão de Nova Tarefa')
    submit = SubmitField('Salvar')

    def validate_padrao_nova(self,padrao_nova):
        situacao = SituacaoSolicitacao.query.filter_by(padrao_nova=1).first()
        if situacao:
            if padrao_nova.data == 1:
                raise ValidationError('Já existe uma situação padrão cadastrada.')

devops/situacao_solicitacao/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, request, Blueprint, flash, redirect,url_for
from devops.models import SituacaoSolicitacao
from devops.situacao_solicitacao.forms import FormularioSituacaoSolicitacao
from devops import db
from flask_login import login_required
from devops.utils.check_roles import require_admin

situacoes_solicitacao = Blueprint('situacoes_solicitacao',__name__)


@situacoes_solicitacao.route('/situacoes_solicitacao')
@login_required
@require_admin()
def situacao_solicitacao_list():
    page = request.args.get('page',1,type=int)
    total = len(SituacaoSolicitacao.query.all())
    per_page = 10
    next = None
    previous = None
    if page > 1:
        previous = page - 1
    if page < total/per_page:
        next = page + 1 
    situacoes_solicitacao = SituacaoSolicitacao.query.paginate(page=page,per_page=per_page)
    return render_template('situacao_solicitacao/list.html',
                            title='Situação Solicitação',
                            situacoes_solicitacao=situacoes_solicitacao,
                            next=next,
                            previous=previous,
                            total=total)

@situacoes_solicitacao.route('/situacao_solicitacao/novo',methods=['GET','POST'])
@login_required
@require_admin()
def situacao_solicitacao_novo():
    form = FormularioSituacaoSolicitacao()
    if form.validate_on_submit():
        situacao_solicitacao = SituacaoSolicitacao(
                descricao=form.descricao.data,
                ativa=form.ativo.data,
                padrao_nova=form.padrao_nova.data)
        db.session.add(situacao_solicitacao)
        db.session.commit()
        flash('Situação Cadastrada.','success')
        return redirect(url_for('situacoes_solicitacao.situacao_solicitacao_list'))
    elif request.method == 'GET':
        return render_template('situacao_solicitacao/new.html',titulo="Nova Situação",form=form)
    else:
        return render_template('situacao_solicitacao/new.html',titulo="Nova Situação",form=form)

@situacoes_solicitacao.route('/situacao_solicitacao/<int:id_situacao_solicitacao>')
@login_required
@require_admin()
def situacao_solicitacao(id_situacao_solicitacao):
    situacao_solicitacao = SituacaoSolicitacao.query.get_or_404(id_situacao_solicitacao)
    form = FormularioSituacaoSolicitacao()
    return render_template('situacao_solicitacao/show.html',situacao_solicitacao=situacao_solicitacao,form=form,title='situacao_solicitacao')   

@situacoes_solicitacao.route('/situacao_solicitacao/<int:id_situacao_solicitacao>/atualizar',methods=['GET'])
@login_required
@require_admin()
def editar_situacao_solicitacao(id_situacao_solicitacao):
    situacao_solicitacao = SituacaoSolicitacao.query.get_or_404(id_situacao_solicitacao)
    form = FormularioSituacaoSolicitacao()
    form.descricao.data = situacao_solicitacao.descricao
    form.ativo.data = situacao_solicitacao.ativa
    form.padrao_nova.data = situacao_solicitacao.padrao_nova
    return render_template('situacao_solicitacao/edit.html',
                            titulo='Atualizar Situação Solicitação',
                            situacao_solicitacao=situacao_solicitacao,
                            form=form,
                            id_situacao_solicitacao=id_situacao_solicitacao)

@situacoes_solicitacao.route('/situacao_solicitacao/<int:id_situacao_solicitacao>/atualizar',methods=['POST'])
@login_required
@require_admin()
def atualizar_situacao_solicitacao(id_situacao_solicitacao):
    situacao_solicitacao = SituacaoSolicitacao.query.get_or_404(id_situacao_solicitacao)
    form = FormularioSituacaoSolicitacao()
    if form.validate_on_submit():
        situacao_solicitacao.descricao = form.descricao.data
        situacao_solicitacao.ativa = form.ativo.data
        situacao_solicitacao.padrao_nova = form.padrao_nova.data
        db.session.commit()
        flash('Registro atualizado!','success')
        return redirect(url_for('situacoes_solicitacao.situacao_solicitacao_list'))
    else:
        return render_template('situacao_solicitacao/edit.html',
                            titulo='Atualizar Situação Solicitação',
                            situacao_solicitacao=situacao_solicitacao,
                            form=form,
                            id_situacao_solicitacao=id_situacao_solicitacao)


@situacoes_solicitacao.route('/situacao_solicitacao/<int:id_situacao_solicitacao>/remover',methods=['GET','POST'])
@login_required
@require_admin()
def remover_situacao_solicitacao(id_situacao_solicitacao):
    print(id_situacao_solicitacao)
    
    situacao_solicitacao = SituacaoSolicitacao.query.get_or_404(id_situacao_solicitacao)
    print(situacao_solicitacao)
    db.session.delete(situacao_solicitacao)
    db.session.commit()
    flash('O registro foi excluído.','success')
    return redirect(url_for('situacoes_solicitacao.situacao_solicitacao_list'))

devops/templates/situacao_solicitacao/edit.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('situacoes_solicitacao.atualizar_situacao_solicitacao',id_situacao_solicitacao=id_situacao_solicitacao)}}">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.descricao.label(class="form-control-label") }}
                                {% if form.descricao.errors %}
                                {{ form.descricao(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.descricao.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.descricao(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                            {% if form.ativo.errors %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.ativo(class="form-check-input is-invalid") }}
                                    {{form.ativo.label}}
                                </label>
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.ativo.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.ativo(class="form-check-input") }}
                                    {{form.ativo.label}}
                                </label>
                            </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if form.padrao_nova.errors %}
                            <div class="form-check mb-3 is-invalid">
                                <label class="form-check-label">
                                    {{ form.padrao_nova(class="form-check-input") }}
                                    {{form.padrao_nova.label}}
                                </label>
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.padrao_nova.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.padrao_nova(class="form-check-input") }}
                                    {{form.padrao_nova.label}}
                                </label>
                            </div>
                            {% endif %}
                        </div>
                            <div class="general-button">
                                    <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list') }}" class="btn btn-secondary md-1">
                                            Voltar
                                        </a>
                                {{ form.submit(class="btn btn-primary md-1") }}
                            </div>
    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

devops/templates/situacao_solicitacao/list.html
{% extends "template.html" %}
{% block conteudo %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                            <h4 class="card-title">{{ title }}</h4>
                            <div class="row">
                                <div class="table-responsive">
                                    {% if situacoes_solicitacao %}
                                    <table class="table table-boredered">
                                        <thead>
                                            <th>#ID</th>
                                            <th>Descrição</th>
                                            <th>Ativo</th>
                                            <th>Ações</th>
                                        </thead>
                                        <tbody>
                                            {% for situacao_solicitacao in situacoes_solicitacao.items %}
                                            <tr>
                                                <td>{{ situacao_solicitacao.id }}</td>
                                                <td>
                                                    <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao',id_situacao_solicitacao=situacao_solicitacao.id) }}">
                                                        {{ situacao_solicitacao.descricao }}
                                                    </a>
                                                </td>
                            
                                                <td>
                                                    {% if situacao_solicitacao.is_ativo() %}
                                                        Ativo
                                                    {% else %}
                                                        Inativo
                                                    {% endif %}
                                                </td>
                            
                                                <td>
                                                        <span>
                                                            <a href="{{ url_for('situacoes_solicitacao.editar_situacao_solicitacao',id_situacao_solicitacao=situacao_solicitacao.id) }}" data-toggle="tooltip" data-placement="top" title="Editar">
                                                                <i class="fa fa-pencil color-muted m-r-5"></i> 
                                                            </a>
                                                            {% if situacao_solicitacao != current_user %}
                                                            <a href="#" data-toggle="modal" data-target="#deleteModal_{{situacao_solicitacao.id}}" data-placement="top" title="Remover">
                                                                <i class="fa fa-close color-danger m-r-5"></i>
                                                            </a>
                                                            <div class="modal fade" id="deleteModal_{{situacao_solicitacao.id}}">
                                                                <div class="modal-dialog" role="document">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title">Excluir</h5>
                                                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body">Deseja realmente excluir esse item?</div>
                                                                        <div class="modal-footer">
                                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                                            <form action="{{ url_for('situacoes_solicitacao.remover_situacao_solicitacao',id_situacao_solicitacao=situacao_solicitacao.id) }}" method="POST">
                                                                                <button type="submit" class="btn btn-primary">Excluir</button>
                                                                            </form>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            {% endif %}
                                                        </span>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    {% else %}
                                        <div class="media align-items-center mb-4">
                                            <div class="media-body">
                                                <h4 class="mb-1 text-muted">Sem itens</h4>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                        </div>
                         
                        <div class="row">
                            {% if situacoes_solicitacao %}
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info">
                                    Total de {{ total }}
                                </div>
                            </div>
                            {% endif %}
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginage paging_simple_numbers">
                                    <ul class="pagination">
                                        {% if previous %}
                                        <li class="paginage_button page-item next">
                                            <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list',page=previous) }}" data-dt-idx="{{previous}}" class=page-link>
                                                Próximo
                                            </a>
                                        </li>
                                        {% endif %}
                                        {% for page_num in situacoes_solicitacao.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
                                            {% if page_num %}
                                            
                                                {% if situacoes_solicitacao.page == page_num %}
                                                    <li class="paginage_button page-item active">
                                                        <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list',page=page_num )}}" data-dt-idx="{{page_num}}" class=page-link>
                                                            {{page_num}}
                                                        </a>
                                                    </li>
                                                {% else %}
                                                    <li class="paginage_button page-item">
                                                        <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list',page=page_num) }}" data-dt-idx="{{page_num}}" class=page-link>
                                                            {{page_num}}
                                                        </a>
                                                    </li>
                                                {% endif %}
                                                
                                            {% else %}
                                                <li class="paginate_button page-item inactive">
                                                     ...
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if next %}
                                            <li class="paginage_button page-item next">
                                                <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list',page=next) }}" data-dt-idx="{{next}}" class=page-link>
                                                    Próximo
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_novo') }}">
                    <button class="btn btn-primary">
                        Novo
                    </button>
                </a> 
            </div>
        </div>
    </div>

{% endblock  %}

devops/templates/situacao_solicitacao/new.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('situacoes_solicitacao.situacao_solicitacao_novo')}}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.descricao.label(class="form-control-label") }}
                            {% if form.descricao.errors %}
                            {{ form.descricao(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.descricao.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.descricao(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if form.ativo.errors %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.ativo(class="form-check-input is-invalid") }}
                                    {{form.ativo.label}}
                                </label>
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.ativo.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.ativo(class="form-check-input") }}
                                    {{form.ativo.label}}
                                </label>
                            </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if form.padrao_nova.errors %}
                            <div class="form-check mb-3 is-invalid">
                                <label class="form-check-label">
                                    {{ form.padrao_nova(class="form-check-input") }}
                                    {{form.padrao_nova.label}}
                                </label>
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.padrao_nova.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    {{ form.padrao_nova(class="form-check-input") }}
                                    {{form.padrao_nova.label}}
                                </label>
                            </div>
                            {% endif %}
                        </div>
                        <div class="general-button">
                                <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list') }}" class="btn btn-secondary md-1">
                                        Voltar
                                    </a>
                            {{ form.submit(class="btn btn-primary md-1") }}
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('descricao').focus();
</script>
{% endblock  %}

devops/templates/situacao_solicitacao/show.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
                    <ul class="card-profile__info">
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.id.label }}:
                            </strong> 
                            <span>
                                {{ situacao_solicitacao.id }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.descricao.label }}:
                            </strong> 
                            <span>
                                {{ situacao_solicitacao.descricao }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.ativo.label }}:
                            </strong> 
                            <span>
                                {% if situacao_solicitacao.is_ativo() %}
                                    Ativo
                                {% else %}
                                    Inativo
                                {% endif %}
                            </span>
                        </li>
                        
                    </ul>
                    <div class="general-button">
                        <a href="{{ url_for('situacoes_solicitacao.situacao_solicitacao_list') }}" class="btn btn-secondary mb-1">
                            Voltar
                        </a>
                        <a href="{{ url_for('situacoes_solicitacao.editar_situacao_solicitacao',id_situacao_solicitacao=situacao_solicitacao.id) }}">
                            <button type="button" class="btn mb-1 btn-primary">
                                Editar
                            </button>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#deleteModal">
                            <button type="button" class="btn mb-1 btn-danger">
                                Excluir
                            </button>
                        </a>
                        <div class="modal fade" id="deleteModal">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Excluir</h5>
                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Deseja realmente excluir esse item?</div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <form action="{{ url_for('situacoes_solicitacao.remover_situacao_solicitacao',id_situacao_solicitacao=situacao_solicitacao.id) }}" method="POST">
                                                <button type="submit" class="btn btn-primary">Excluir</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}