devops/tipo_sgbd/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,HiddenField, IntegerField
from wtforms.validators import DataRequired,ValidationError
from devops.models import TipoSGBD


class FormularioTipoSGBD(FlaskForm):
    id = IntegerField('ID')
    descricao = StringField('Descrição', validators=[DataRequired()])                   
    formato_url = StringField('Formato URL', validators=[DataRequired()])                   
    porta_padrao = IntegerField('Porta Padrão')
    submit = SubmitField('Salvar')  

    def validate_porta_padrao(self,porta_padrao):
        if not str(porta_padrao.data).isnumeric():
            raise ValidationError('Apenas números são permitidos.')

devops/tipo_sgbd/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, request, Blueprint, flash, redirect,url_for
from devops.models import TipoSGBD
from devops.tipo_sgbd.forms import FormularioTipoSGBD
from devops import db
from flask_login import login_required
from devops.utils.check_roles import require_admin

tipos_sgbd = Blueprint('tipos_sgbd',__name__)


@tipos_sgbd.route('/tipos_sgbd')
@login_required
@require_admin()
def tipo_sgbd_list():
    page = request.args.get('page',1,type=int)
    total = len(TipoSGBD.query.all())
    per_page = 10
    next = None
    previous = None
    if page > 1:
        previous = page - 1
    if page < total/per_page:
        next = page + 1 
    tipos_sgbd = TipoSGBD.query.paginate(page=page,per_page=per_page)
    return render_template('tipo_sgbd/list.html',
                            title='Tipos de SGBD',
                            tipos_sgbd=tipos_sgbd,
                            next=next,
                            previous=previous,
                            total=total)

@tipos_sgbd.route('/tipo_sgbd/novo',methods=['GET','POST'])
@login_required
@require_admin()
def tipo_sgbd_novo():
    form = FormularioTipoSGBD()
    if form.validate_on_submit():
        tipo_sgbd = TipoSGBD(descricao=form.descricao.data,formato_url=form.formato_url.data,porta_padrao=form.porta_padrao.data)
        db.session.add(tipo_sgbd)
        db.session.commit()
        flash('Tipo de SGBD cadastrada.','success')
        return redirect(url_for('tipos_sgbd.tipo_sgbd_list'))
    elif request.method == 'GET':
        return render_template('tipo_sgbd/new.html',titulo="Novo Tipo de SGBD",form=form)
    else:
        return render_template('tipo_sgbd/new.html',titulo="Novo Tipo de SGBD",form=form)

@tipos_sgbd.route('/tipo_sgbd/<int:id_tipo_sgbd>')
@login_required
@require_admin()
def tipo_sgbd(id_tipo_sgbd):
    tipo_sgbd = TipoSGBD.query.get_or_404(id_tipo_sgbd)
    form = FormularioTipoSGBD()
    form.id.data = tipo_sgbd.id
    form.descricao.data = tipo_sgbd.descricao
    form.formato_url.data = tipo_sgbd.formato_url
    form.porta_padrao.data = tipo_sgbd.porta_padrao
    return render_template('tipo_sgbd/show.html',tipo_sgbd=tipo_sgbd,form=form,title='Tipo de SGBD')

@tipos_sgbd.route('/tipo_sgbd/<int:id_tipo_sgbd>/atualizar',methods=['GET'])
@login_required
@require_admin()
def editar_tipo_sgbd(id_tipo_sgbd):
    tipo_sgbd = TipoSGBD.query.get_or_404(id_tipo_sgbd)
    form = FormularioTipoSGBD()
    form.descricao.data = tipo_sgbd.descricao
    form.formato_url.data = tipo_sgbd.formato_url
    form.porta_padrao.data = tipo_sgbd.porta_padrao
    return render_template('tipo_sgbd/edit.html',
                            titulo='Atualizar Tipo de SGBD',
                            tipo_sgbd=tipo_sgbd,
                            form=form,
                            id_tipo_sgbd=id_tipo_sgbd)

@tipos_sgbd.route('/tipo_sgbd/<int:id_tipo_sgbd>/atualizar',methods=['POST'])
@login_required
@require_admin()
def atualizar_tipo_sgbd(id_tipo_sgbd):
    tipo_sgbd = TipoSGBD.query.get_or_404(id_tipo_sgbd)
    form = FormularioTipoSGBD()
    if form.validate_on_submit():
        tipo_sgbd.descricao = form.descricao.data
        tipo_sgbd.formato_url = form.formato_url.data
        tipo_sgbd.porta_padrao = form.porta_padrao.data 
        db.session.commit()
        flash('Registro atualizado!','success')
        return redirect(url_for('tipos_sgbd.tipo_sgbd_list'))
    else:
        return render_template('tipo_sgbd/edit.html',
                            titulo='Atualizar Tipo de SGBD',
                            tipo_sgbd=tipo_sgbd,
                            form=form,
                            id_tipo_sgbd=id_tipo_sgbd)


@tipos_sgbd.route('/tipo_sgbd/<int:id_tipo_sgbd>/remover',methods=['GET','POST'])
@login_required
@require_admin()
def remover_tipo_sgbd(id_tipo_sgbd):
    print(id_tipo_sgbd)
    
    tipo_sgbd = TipoSGBD.query.get_or_404(id_tipo_sgbd)
    print(tipo_sgbd)
    db.session.delete(tipo_sgbd)
    db.session.commit()
    flash('O registro foi excluído.','success')
    return redirect(url_for('tipos_sgbd.tipo_sgbd_list'))
    

devops/templates/tipo_sgbd/edit.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('tipos_sgbd.atualizar_tipo_sgbd',id_tipo_sgbd=id_tipo_sgbd)}}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.descricao.label(class="form-control-label") }}
                            {{ form.descricao(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.formato_url.label(class="form-control-label") }}
                            {{ form.formato_url(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.porta_padrao.label(class="form-control-label") }}
                            {{ form.porta_padrao(class="form-control") }}
                        </div>
                        <div class="general-button">
                            <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list') }}" class="btn btn-secondary mb-1">
                                Voltar
                            </a>

                            {{ form.submit(class="btn btn-primary mb-1") }}

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

devops/templates/tipo_sgbd/list.html
{% extends "template.html" %}
{% block conteudo %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                            <h4 class="card-title">{{ title }}</h4>
                            <div class="row">
                                <div class="table-responsive">
                                    {% if tipos_sgbd.items %}
                                    <table class="table table-boredered">
                                        <thead>
                                            <th>#ID</th>
                                            <th>Descrição</th>
                                            <th>Ações</th>
                                        </thead>
                                        <tbody>
                                            {% for tipo_sgbd in tipos_sgbd.items %}
                                            <tr>
                                                <td>{{ tipo_sgbd.id }}</td>
                                                <td>
                                                    <a href="{{ url_for('tipos_sgbd.tipo_sgbd',id_tipo_sgbd=tipo_sgbd.id) }}">
                                                        {{ tipo_sgbd.descricao }}
                                                    </a>
                                                </td>
                                                
                                                <td>
                                                        <span>
                                                            <a href="{{ url_for('tipos_sgbd.editar_tipo_sgbd',id_tipo_sgbd=tipo_sgbd.id) }}" data-toggle="tooltip" data-placement="top" title="Editar">
                                                                <i class="fa fa-pencil color-muted m-r-5"></i> 
                                                            </a>
                                                            <a href="#" data-toggle="modal" data-target="#deleteModal_{{tipo_sgbd.id}}" data-placement="top" title="Remover">
                                                                <i class="fa fa-close color-danger m-r-5"></i>
                                                            </a>
                                                            <div class="modal fade" id="deleteModal_{{tipo_sgbd.id}}">
                                                                <div class="modal-dialog" role="document">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title">Excluir</h5>
                                                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body">Deseja realmente excluir esse item?</div>
                                                                        <div class="modal-footer">
                                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                                            <form action="{{ url_for('tipos_sgbd.remover_tipo_sgbd',id_tipo_sgbd=tipo_sgbd.id) }}" method="POST">
                                                                                <button type="submit" class="btn btn-primary">Excluir</button>
                                                                            </form>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </span>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    {% else %}
                                        <div class="media align-items-center mb-4">
                                            <div class="media-body">
                                                <h4 class="mb-1 text-muted">Sem itens</h4>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                        </div>
                         
                        <div class="row">
                            {% if tipos_sgbd.items %}
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info">
                                    Total de {{ total }}
                                </div>
                            </div>
                            {% endif %}
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginage paging_simple_numbers">
                                    <ul class="pagination">
                                        {% if previous %}
                                        <li class="paginage_button page-item next">
                                            <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list',page=previous) }}" data-dt-idx="{{previous}}" class=page-link>
                                                Próximo
                                            </a>
                                        </li>
                                        {% endif %}
                                        {% for page_num in tipos_sgbd.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
                                            {% if page_num %}
                                            
                                                {% if tipos_sgbd.page == page_num %}
                                                    <li class="paginage_button page-item active">
                                                        <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list',page=page_num )}}" data-dt-idx="{{page_num}}" class=page-link>
                                                            {{page_num}}
                                                        </a>
                                                    </li>
                                                {% else %}
                                                    <li class="paginage_button page-item">
                                                        <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list',page=page_num) }}" data-dt-idx="{{page_num}}" class=page-link>
                                                            {{page_num}}
                                                        </a>
                                                    </li>
                                                {% endif %}
                                                
                                            {% else %}
                                                <li class="paginate_button page-item inactive">
                                                     ...
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if next %}
                                            <li class="paginage_button page-item next">
                                                <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list',page=next) }}" data-dt-idx="{{next}}" class=page-link>
                                                    Próximo
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ url_for('tipos_sgbd.tipo_sgbd_novo') }}">
                    <button class="btn btn-primary">
                        Novo
                    </button>
                </a> 
            </div>
        </div>
    </div>

{% endblock  %}

devops/templates/tipo_sgbd/new.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('tipos_sgbd.tipo_sgbd_novo')}}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.descricao.label(class="form-control-label") }}
                            {% if form.descricao.errors %}
                            {{ form.descricao(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.descricao.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.descricao(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.formato_url.label(class="form-control-label") }}
                            {% if form.formato_url.errors %}
                            {{ form.formato_url(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.formato_url.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.formato_url(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.porta_padrao.label(class="form-control-label") }}
                            {% if form.porta_padrao.errors %}
                            {{ form.porta_padrao(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.porta_padrao.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.porta_padrao(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="general-button">
                            <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list') }}" class="btn btn-secondary mb-1">
                                Voltar
                            </a>
                            {{ form.submit(class="btn btn-primary mb-1") }}
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('descricao').focus();
</script>
{% endblock  %}

devops/templates/tipo_sgbd/show.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
                    <ul class="card-profile__info">
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.id.label }}:
                            </strong>
                            <span>
                                {{ form.id.data }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.descricao.label }}:
                            </strong>
                            <span>
                                {{ form.descricao.data }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.formato_url.label }}:
                            </strong>
                            <span>
                                {{ form.formato_url.data }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.porta_padrao.label }}:
                            </strong>
                            <span>
                                {{ form.porta_padrao.data }}
                            </span>
                        </li>
                    </ul>
                    <div class="general-button">
                        <a href="{{ url_for('tipos_sgbd.tipo_sgbd_list') }}" class="btn btn-secondary mb-1">
                            Voltar
                        </a>
                        <a href="{{ url_for('tipos_sgbd.editar_tipo_sgbd',id_tipo_sgbd=form.id.data) }}">
                            <button type="button" class="btn mb-1 btn-primary">
                                Editar
                            </button>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#deleteModal">
                            <button type="button" class="btn mb-1 btn-danger">
                                Excluir
                            </button>
                        </a>
                        <div class="modal fade" id="deleteModal">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Excluir</h5>
                                        <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">Deseja realmente excluir esse item?</div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Cancelar</button>
                                        <form action="{{ url_for('tipos_sgbd.remover_tipo_sgbd',id_tipo_sgbd=form.id.data) }}"
                                            method="POST">
                                            <button type="submit" class="btn btn-primary">Excluir</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}