devops/banco_trabalho/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,HiddenField, IntegerField,SelectField,PasswordField
from wtforms.validators import DataRequired
from devops.models import BancoTrabalho
from devops.utils.validators import IPValidator

class FormularioBancoTrabalho(FlaskForm):
    nome = StringField('Nome',
                            validators=[DataRequired()])                            
    tipo_sgbd = SelectField('SGBD', 
                            validators=[DataRequired()])
    host_name = StringField('Hostname',
                            validators=[DataRequired(),IPValidator()])
    porta = IntegerField('Porta', validators=[DataRequired()])
    nome_database = StringField('Nome do Banco',validators=[DataRequired()])
    usuario_database = StringField('Usuario Banco',validators=[DataRequired()])
    senha_database = StringField('Senha Banco',validators=[DataRequired()])
    tipo_sgbd = SelectField('Tipo de SGBD', 
                            validators=[DataRequired()],coerce=int)
    ambiente = SelectField('Ambiente', 
                            validators=[DataRequired()],coerce=int)
    
    submit = SubmitField('Salvar')  

devops/banco_trabalho/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, request, Blueprint, flash, redirect,url_for
from devops.models import BancoTrabalho,TipoSGBD,AmbienteBanco
from devops.banco_trabalho.forms import FormularioBancoTrabalho
from devops import db,app
from flask_login import login_required
from devops.utils.check_roles import require_admin

bancos_trabalho = Blueprint('bancos_trabalho',__name__)


@bancos_trabalho.route('/bancos_trabalho')
@login_required
@require_admin()
def banco_trabalho_list():
    page = request.args.get('page',1,type=int)
    total = len(BancoTrabalho.query.all())
    per_page = 10
    next = None
    previous = None
    if page > 1:
        previous = page - 1
    if page < total/per_page:
        next = page + 1 
    bancos_trabalho = BancoTrabalho.query.paginate(page=page,per_page=per_page)
    return render_template('banco_trabalho/list.html',
                            title='Banco de Trabalho',
                            bancos_trabalho=bancos_trabalho,
                            next=next,
                            previous=previous,
                            total=total)

@bancos_trabalho.route('/banco_trabalho/novo',methods=['GET','POST'])
@login_required
@require_admin()
def banco_trabalho_novo():
    form = FormularioBancoTrabalho()
    form.tipo_sgbd.choices = [(ts.id,ts.descricao) for ts in TipoSGBD.query.all()]
    form.ambiente.choices = [(ab.id,ab.descricao) for ab in AmbienteBanco.query.all()]
    if form.validate_on_submit():
        form = FormularioBancoTrabalho()
        banco_trabalho = BancoTrabalho(
                                        nome=form.nome.data,
                                        host_name=form.host_name.data,
                                        porta=form.porta.data,
                                        nome_database=form.nome_database.data, 
                                        usuario_database=form.usuario_database.data,
                                        senha_database=form.senha_database.data,
                                        id_ambiente_banco=form.ambiente.data,
                                        id_tipo_sgbd=form.tipo_sgbd.data   
                                    )
        db.session.add(banco_trabalho)
        db.session.commit()
        flash('Banco de Trabalho Cadastrado.','success')
        return redirect(url_for('bancos_trabalho.banco_trabalho_list'))
    elif request.method == 'GET':
        return render_template('banco_trabalho/new.html',titulo="Novo banco de trabalho",form=form)
    else:
        return render_template('banco_trabalho/new.html',titulo="Novo banco de trabalho",form=form)

@bancos_trabalho.route('/banco_trabalho/<int:id_banco_trabalho>')
@login_required
@require_admin()
def banco_trabalho(id_banco_trabalho):
    banco_trabalho = BancoTrabalho.query.get_or_404(id_banco_trabalho)
    form = FormularioBancoTrabalho()
    return render_template('banco_trabalho/show.html',banco_trabalho=banco_trabalho,form=form,title='Banco de Trabalho')

@bancos_trabalho.route('/banco_trabalho/<int:id_banco_trabalho>/atualizar',methods=['GET'])
@login_required
@require_admin()
def editar_banco_trabalho(id_banco_trabalho):
    banco_trabalho = BancoTrabalho.query.get_or_404(id_banco_trabalho)
    form = FormularioBancoTrabalho()
    form.nome.data = banco_trabalho.nome
    form.host_name.data = banco_trabalho.host_name
    form.porta.data = banco_trabalho.porta
    form.nome_database.data = banco_trabalho.nome_database
    form.usuario_database.data = banco_trabalho.usuario_database
    form.senha_database.data = banco_trabalho.senha_database
    form.tipo_sgbd.choices = [(ts.id,ts.descricao) for ts in TipoSGBD.query.all()]
    form.tipo_sgbd.data = banco_trabalho.id_tipo_sgbd
    form.ambiente.choices = [(ab.id,ab.descricao) for ab in AmbienteBanco.query.all()]
    form.ambiente.data = banco_trabalho.id_ambiente_banco

    return render_template('banco_trabalho/edit.html',
                            titulo='Atualizar Banco de Trabalho',
                            banco_trabalho=banco_trabalho,
                            form=form,
                            id_banco_trabalho=id_banco_trabalho)

@bancos_trabalho.route('/banco_trabalho/<int:id_banco_trabalho>/atualizar',methods=['POST'])
@login_required
@require_admin()
def atualizar_banco_trabalho(id_banco_trabalho):
    banco_trabalho = BancoTrabalho.query.get_or_404(id_banco_trabalho)
    form = FormularioBancoTrabalho()
    form.tipo_sgbd.choices = [(ts.id,ts.descricao) for ts in TipoSGBD.query.all()]
    form.ambiente.choices = [(ab.id,ab.descricao) for ab in AmbienteBanco.query.all()]
    if form.validate_on_submit():
        
        banco_trabalho.nome = form.nome.data
        banco_trabalho.host_name = form.host_name.data
        banco_trabalho.porta = form.porta.data
        banco_trabalho.nome_database = form.nome_database.data
        banco_trabalho.usuario_database = form.usuario_database.data
        banco_trabalho.senha_database= form.senha_database.data
        banco_trabalho.id_tipo_sgbd = form.tipo_sgbd.data
        banco_trabalho.id_ambiente_banco = form.ambiente.data
        
        db.session.commit()
        flash('Registro atualizado!','success')
        return redirect(url_for('bancos_trabalho.banco_trabalho_list'))
    else:
        return render_template('banco_trabalho/edit.html',
                            titulo='Atualizar Banco de Trabalho',
                            banco_trabalho=banco_trabalho,
                            form=form,
                            id_banco_trabalho=id_banco_trabalho)


@bancos_trabalho.route('/banco_trabalho/<int:id_banco_trabalho>/remover',methods=['GET','POST'])
@login_required
@require_admin()
def remover_banco_trabalho(id_banco_trabalho):
    print(id_banco_trabalho)
    banco_trabalho = BancoTrabalho.query.get_or_404(id_banco_trabalho)
    db.session.delete(banco_trabalho)
    db.session.commit()
    flash('O registro foi excluído.','success')
    return redirect(url_for('bancos_trabalho.banco_trabalho_list'))
    

devops/templates/banco_trabalho/edit.html
{% extends "template.html" %}
{% block conteudo %}
<style>
    .field-icon {
        float: right;
        margin-left: -25px;
        margin-top: -25px;
        position: relative;
        z-index: 2;
    }
    

</style>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ titulo }} </h4>
                    <form method="POST" action="{{url_for('bancos_trabalho.atualizar_banco_trabalho',id_banco_trabalho=id_banco_trabalho)}}">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.nome.label(class="form-control-label") }}
                                {% if form.nome.errors %}
                                    {{ form.nome(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.nome.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.nome(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.host_name.label(class="form-control-label") }}
                                {% if form.host_name.errors %}
                                    {{ form.host_name(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.host_name.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.host_name(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.porta.label(class="form-control-label") }}
                                {% if form.porta.errors %}
                                    {{ form.porta(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.porta.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.porta(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.nome_database.label(class="form-control-label") }}
                                {% if form.nome_database.errors %}
                                    {{ form.nome_database(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.nome_database.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.nome_database(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.usuario_database.label(class="form-control-label") }}
                                {% if form.usuario_database.errors %}
                                    {{ form.usuario_database(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.usuario_database.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.usuario_database(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group" id='senha'>
                                {{ form.senha_database.label(class="form-control-label") }}
                                {% if form.senha_database.errors %}
                                    {{ form.senha_database(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.senha_database.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.senha_database(class="form-control") }}
                                    <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password">
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.tipo_sgbd.label(class="form-control-label") }}
                                {% if form.tipo_sgbd.errors %}
                                    {{ form.tipo_sgbd(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.tipo_sgbd.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.tipo_sgbd(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.ambiente.label(class="form-control-label") }}
                                {% if form.ambiente.errors %}
                                    {{ form.ambiente(class="form-control is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.ambiente.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.ambiente(class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="general-button">
                                <a href="{{ url_for('bancos_trabalho.banco_trabalho_list') }}" class="btn mb-1 btn-secondary">
                                    Voltar
                                </a>
                                {{ form.submit(class="btn mb-1 btn-primary") }}
                            </div>
                            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
        var input = document.querySelector('#senha input');
        var img = document.querySelector('#senha span');
        img.addEventListener('click', function () {
          input.type = input.type == 'text' ? 'password' : 'text';
        });

</script>
{% endblock  %}

devops/templates/banco_trabalho/list.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                        <h4 class="card-title">{{ title }}</h4>
                        <div class="row">
                            <div class="table-responsive">
                                {% if bancos_trabalho.items %}
                                <table class="table table-boredered">
                                    <thead>
                                        <th>#ID</th>
                                        <th>Nome</th>
                                        <th>HostName</th>
                                        <th>Porta</th>
                                        <th>Database</th>
                                        <th>Tipo</th>
                                        <th>Ambiente</th>
                                        <th>Ações</th>
                                    </thead>
                                    <tbody>
                                        {% for banco_trabalho in bancos_trabalho.items %}
                                        <tr>
                                            <td>{{ banco_trabalho.id }}</td>
                                            <td>
                                                <a href="{{ url_for('bancos_trabalho.banco_trabalho',id_banco_trabalho=banco_trabalho.id) }}">
                                                    {{ banco_trabalho.nome }}
                                                </a>
                                            </td>
                                            <td>{{ banco_trabalho.host_name }}</td>
                                            <td>{{ banco_trabalho.porta }}</td>
                                            <td>{{ banco_trabalho.nome_database }}</td>
                                            <td>{{ banco_trabalho.tipo_sgbd.descricao}}</td>
                                            <td>{{ banco_trabalho.ambiente_banco.descricao }}</td>
                                            <td>
                                                    <span>
                                                        <a href="{{ url_for('bancos_trabalho.editar_banco_trabalho',id_banco_trabalho=banco_trabalho.id) }}" data-toggle="tooltip" data-placement="top" title="Editar">
                                                            <i class="fa fa-pencil color-muted m-r-5"></i> 
                                                        </a>
                                                        <a href="#" data-toggle="modal" data-target="#deleteModal_{{banco_trabalho.id}}" data-placement="top" title="Remover">
                                                            <i class="fa fa-close color-danger m-r-5"></i>
                                                        </a>
                                                        <div class="modal fade" id="deleteModal_{{banco_trabalho.id}}">
                                                            <div class="modal-dialog" role="document">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title">Excluir</h5>
                                                                        <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                                                        </button>
                                                                    </div>
                                                                    <div class="modal-body">Deseja realmente excluir esse item?</div>
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                                        <form action="{{ url_for('bancos_trabalho.remover_banco_trabalho',id_banco_trabalho=banco_trabalho.id) }}" method="POST">
                                                                            <button type="submit" class="btn btn-primary">Excluir</button>
                                                                        </form>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}
                                    <div class="media align-items-center mb-4">
                                        <div class="media-body">
                                            <h4 class="mb-1 text-muted">Sem itens</h4>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                    </div>
                        
                    <div class="row">
                        {% if bancos_trabalho.items %}
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info">
                                Total de {{ total }}
                            </div>
                        </div>
                        {% endif %}
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginage paging_simple_numbers">
                                <ul class="pagination">
                                    {% if previous %}
                                    <li class="paginage_button page-item next">
                                        <a href="{{ url_for('bancos_trabalho.banco_trabalho_list',page=previous) }}" data-dt-idx="{{previous}}" class=page-link>
                                            Próximo
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% for page_num in bancos_trabalho.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
                                        {% if page_num %}
                                        
                                            {% if bancos_trabalho.page == page_num %}
                                                <li class="paginage_button page-item active">
                                                    <a href="{{ url_for('bancos_trabalho.banco_trabalho_list',page=page_num )}}" data-dt-idx="{{page_num}}" class=page-link>
                                                        {{page_num}}
                                                    </a>
                                                </li>
                                            {% else %}
                                                <li class="paginage_button page-item">
                                                    <a href="{{ url_for('bancos_trabalho.banco_trabalho_list',page=page_num) }}" data-dt-idx="{{page_num}}" class=page-link>
                                                        {{page_num}}
                                                    </a>
                                                </li>
                                            {% endif %}
                                            
                                        {% else %}
                                            <li class="paginate_button page-item inactive">
                                                    ...
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if next %}
                                        <li class="paginage_button page-item next">
                                            <a href="{{ url_for('bancos_trabalho.banco_trabalho_list',page=next) }}" data-dt-idx="{{next}}" class=page-link>
                                                Próximo
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>
    <div class="row">
        <div class="col-lg-12">
            <a href="{{ url_for('bancos_trabalho.banco_trabalho_novo') }}">
                <button class="btn btn-primary">
                    Novo
                </button>
            </a> 
        </div>
    </div>
</div>

{% endblock  %}

devops/templates/banco_trabalho/show.html
{% extends "template.html" %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
                    <ul class="card-profile__info">
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                ID
                            </strong> 
                            <span>
                                {{ banco_trabalho.id }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.nome.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.nome }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.host_name.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.host_name }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.porta.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.porta }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.nome_database.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.nome_database }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.usuario_database.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.usuario_database }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.tipo_sgbd.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.tipo_sgbd.descricao }}
                            </span>
                        </li>
                        <li class="mb-1">
                            <strong class="text-dark mr-4">
                                {{ form.ambiente.label }}:
                            </strong> 
                            <span>
                                {{ banco_trabalho.ambiente_banco.descricao }}
                            </span>
                        </li>
                    </ul>
                    <li class="mb-1">
                        <strong class="text-dark mr-4">
                            {{ form.nome.label }}:
                        </strong> 
                        <span>
                            {{ form.nome.data }}
                        </span>
                    </li>
                    <div class="general-button">
                        <a href="{{ url_for('bancos_trabalho.banco_trabalho_list') }}" class="btn mb-1 btn-secondary">
                                Voltar
                        </a>
                        <a href="{{ url_for('bancos_trabalho.editar_banco_trabalho',id_banco_trabalho=banco_trabalho.id) }}">
                            <button type="button" class="btn mb-1 btn-primary">
                                Editar
                            </button>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#deleteModal">
                            <button type="button" class="btn mb-1 btn-danger">
                                Excluir
                            </button>
                        </a>
                        <div class="modal fade" id="deleteModal">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Excluir</h5>
                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Deseja realmente excluir esse item?</div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <form action="{{ url_for('bancos_trabalho.remover_banco_trabalho',id_banco_trabalho=banco_trabalho.id) }}" method="POST">
                                                <button type="submit" class="btn btn-primary">Excluir</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}